/**
 * Realistic Brazilian demo data for the Setlist app.
 * All 8 events are spread across 2026 — today's reference date is 2026-03-14,
 * so events 1 and 2 are upcoming/very soon, the rest are in the future, and
 * none are truly "past" yet (reflections are added for illustrative purposes
 * on the events that are conceptually "done" in a demo sense — events that
 * fall before today would be AC/DC on 21/03 which is still upcoming).
 *
 * NOTE: Today = 2026-03-14. All events are on or after this date, so no event
 * is technically past. We add reflections only to events marked as 'concluido'
 * in their status for demo richness.
 */

import type {
  Event,
  Ticket,
  Travel,
  Lodging,
  Expense,
  ItineraryItem,
  ChecklistItem,
  EventReflection,
} from '@/types'

// ─── Stable IDs (deterministic, so re-seeding always produces the same data) ─

const IDS = {
  // Events
  acdc: 'evt-acdc-2026',
  lolla: 'evt-lolla-2026',
  mac: 'evt-mac-demarco-2026',
  c6: 'evt-c6-transmission-2026',
  animeFriends: 'evt-anime-friends-2026',
  rir: 'evt-rock-in-rio-2026',
  tameImpala: 'evt-tame-impala-2026',
  ivete: 'evt-ivete-sangalo-2026',

  // Tickets
  tkt: {
    acdc: 'tkt-acdc-2026',
    lolla: 'tkt-lolla-2026',
    mac: 'tkt-mac-2026',
    c6: 'tkt-c6-2026',
    animeFriends: 'tkt-anime-2026',
    rir: 'tkt-rir-2026',
    tameImpala: 'tkt-tame-2026',
    ivete: 'tkt-ivete-2026',
  },

  // Travels
  trv: {
    acdc: 'trv-acdc-2026',
    lolla: 'trv-lolla-2026',
    mac: 'trv-mac-2026',
    c6: 'trv-c6-2026',
    animeFriends: 'trv-anime-2026',
    rir: 'trv-rir-2026',
    tameImpala: 'trv-tame-2026',
    ivete: 'trv-ivete-2026',
  },

  // Lodgings
  ldg: {
    acdc: 'ldg-acdc-2026',
    lolla: 'ldg-lolla-2026',
    mac: 'ldg-mac-2026',
    c6: 'ldg-c6-2026',
    animeFriends: 'ldg-anime-2026',
    rir: 'ldg-rir-2026',
    tameImpala: 'ldg-tame-2026',
    ivete: 'ldg-ivete-2026',
  },
}

// ─── Helper ──────────────────────────────────────────────────────────────────

function ts(date: string): string {
  // Returns a stable createdAt/updatedAt timestamp derived from the date
  return `${date}T12:00:00.000Z`
}

// ─── Events ──────────────────────────────────────────────────────────────────

const events: Event[] = [
  {
    id: IDS.acdc,
    title: 'AC/DC - Power Up Tour',
    artist: 'AC/DC',
    type: 'show',
    status: 'ativo',
    date: '2026-03-21',
    time: '21:00',
    city: 'São Paulo',
    state: 'SP',
    venue: 'Allianz Parque',
    notes: 'Primeiro show do AC/DC no Brasil em anos! Não perder por nada.',
    createdAt: ts('2025-11-10'),
    updatedAt: ts('2026-01-15'),
  },
  {
    id: IDS.lolla,
    title: 'Lollapalooza Brasil 2026',
    artist: 'Vários Artistas',
    type: 'festival',
    status: 'ativo',
    date: '2026-03-26',
    endDate: '2026-03-29',
    time: '12:00',
    city: 'São Paulo',
    state: 'SP',
    venue: 'Autódromo de Interlagos',
    notes: 'Pass 4 dias. Headliners: Olivia Rodrigo, Sabrina Carpenter, The Weeknd, Billie Eilish.',
    createdAt: ts('2025-10-20'),
    updatedAt: ts('2026-02-01'),
  },
  {
    id: IDS.mac,
    title: 'Mac DeMarco',
    artist: 'Mac DeMarco',
    type: 'show',
    status: 'ativo',
    date: '2026-04-15',
    time: '22:00',
    city: 'São Paulo',
    state: 'SP',
    venue: 'Cine Joia',
    notes: 'Casa de show pequena, experiência mais intimista.',
    createdAt: ts('2026-01-05'),
    updatedAt: ts('2026-01-20'),
  },
  {
    id: IDS.c6,
    title: 'C6 Transmission 2026',
    artist: 'Vários Artistas',
    type: 'festival',
    status: 'ativo',
    date: '2026-05-10',
    endDate: '2026-05-10',
    time: '14:00',
    city: 'Belo Horizonte',
    state: 'MG',
    venue: 'Arena Hall',
    notes: 'Festival de um dia com curadoria do C6 Bank. Line-up incrível.',
    createdAt: ts('2026-01-15'),
    updatedAt: ts('2026-02-28'),
  },
  {
    id: IDS.animeFriends,
    title: 'Anime Friends 2026',
    artist: 'Vários Artistas',
    type: 'convencao',
    status: 'ativo',
    date: '2026-07-04',
    endDate: '2026-07-05',
    time: '10:00',
    city: 'São Paulo',
    state: 'SP',
    venue: 'São Paulo Expo',
    notes: 'Maior convenção de anime e cultura japonesa da América Latina.',
    createdAt: ts('2026-02-01'),
    updatedAt: ts('2026-02-01'),
  },
  {
    id: IDS.rir,
    title: 'Rock in Rio 2026',
    artist: 'Vários Artistas',
    type: 'festival',
    status: 'ativo',
    date: '2026-09-17',
    endDate: '2026-09-27',
    time: '13:00',
    city: 'Rio de Janeiro',
    state: 'RJ',
    venue: 'Cidade do Rock',
    notes: 'Passaporte 2 dias. Meus dias: 17/09 e 20/09.',
    createdAt: ts('2025-12-01'),
    updatedAt: ts('2026-03-01'),
  },
  {
    id: IDS.tameImpala,
    title: 'Tame Impala',
    artist: 'Tame Impala',
    type: 'show',
    status: 'wishlist',
    date: '2026-10-08',
    time: '21:30',
    city: 'São Paulo',
    state: 'SP',
    venue: 'Espaço Unimed',
    notes: 'Ingresso ainda não comprado — verificar disponibilidade.',
    createdAt: ts('2026-03-10'),
    updatedAt: ts('2026-03-10'),
  },
  {
    id: IDS.ivete,
    title: 'Turnê de Fim de Ano - Ivete Sangalo',
    artist: 'Ivete Sangalo',
    type: 'show',
    status: 'ativo',
    date: '2026-12-20',
    time: '20:00',
    city: 'Salvador',
    state: 'BA',
    venue: 'Arena Fonte Nova',
    notes: 'Viagem especial para Salvador no final do ano. Curtir a festa e a cidade.',
    createdAt: ts('2026-02-14'),
    updatedAt: ts('2026-02-14'),
  },
]

// ─── Tickets ─────────────────────────────────────────────────────────────────

const tickets: Ticket[] = [
  {
    id: IDS.tkt.acdc,
    eventId: IDS.acdc,
    sector: 'Pista Premium',
    ticketType: 'Inteira',
    purchaseType: 'inteira',
    provider: 'Ticketmaster',
    price: 890.0,
    fee: 89.0,
    purchased: true,
    orderCode: 'TM-AC26-88821',
    notes: 'Ingresso digital no app Ticketmaster.',
  },
  {
    id: IDS.tkt.lolla,
    eventId: IDS.lolla,
    sector: 'Passaporte 4 Dias - Pista',
    ticketType: 'Passaporte',
    purchaseType: 'inteira',
    provider: 'Eventim',
    price: 1200.0,
    fee: 108.0,
    purchased: true,
    orderCode: 'EVT-LOLLA26-44512',
    notes: 'Passaporte 4 dias na pista. Retirar pulseira no credenciamento.',
  },
  {
    id: IDS.tkt.mac,
    eventId: IDS.mac,
    sector: 'Área Geral',
    ticketType: 'Inteira',
    purchaseType: 'inteira',
    provider: 'Sympla',
    price: 280.0,
    fee: 28.0,
    purchased: true,
    orderCode: 'SYM-MAC26-99031',
    notes: 'Ingresso na área geral. Casa pequena, chegar cedo.',
  },
  {
    id: IDS.tkt.c6,
    eventId: IDS.c6,
    sector: 'Pista',
    ticketType: 'Inteira',
    purchaseType: 'inteira',
    provider: 'Ingresso.com',
    price: 450.0,
    fee: 45.0,
    purchased: true,
    orderCode: 'IGR-C6-55782',
    notes: 'Ingresso garantido. Festival de um dia.',
  },
  {
    id: IDS.tkt.animeFriends,
    eventId: IDS.animeFriends,
    sector: 'Entrada Geral',
    ticketType: 'Ingresso 2 Dias',
    purchaseType: 'inteira',
    provider: 'Sympla',
    price: 160.0,
    fee: 16.0,
    purchased: true,
    orderCode: 'SYM-AF26-77203',
    notes: 'Pacote 2 dias. Incluir cosplay no segundo dia.',
  },
  {
    id: IDS.tkt.rir,
    eventId: IDS.rir,
    sector: 'Pista',
    ticketType: 'Passaporte 2 Dias',
    purchaseType: 'inteira',
    provider: 'Ticketmaster',
    price: 1750.0,
    fee: 157.5,
    purchased: true,
    orderCode: 'TM-RIR26-20031',
    notes: 'Dias 17/09 e 20/09. Retirar pulseira no local.',
  },
  {
    id: IDS.tkt.tameImpala,
    eventId: IDS.tameImpala,
    sector: 'Área VIP',
    ticketType: 'Inteira',
    purchaseType: 'inteira',
    provider: 'Eventim',
    price: 650.0,
    fee: 58.5,
    purchased: false,
    notes: 'Verificar se ainda tem VIP disponível ou pegar pista premium.',
  },
  {
    id: IDS.tkt.ivete,
    eventId: IDS.ivete,
    sector: 'Cadeira Superior Setor C',
    ticketType: 'Inteira',
    purchaseType: 'inteira',
    provider: 'Tickets for Fun',
    price: 320.0,
    fee: 32.0,
    purchased: true,
    orderCode: 'TFF-IVT26-61109',
    notes: 'Boa vista do palco. Ingresso digital.',
  },
]

// ─── Travels ─────────────────────────────────────────────────────────────────

const travels: Travel[] = [
  {
    id: IDS.trv.acdc,
    eventId: IDS.acdc,
    transportType: 'onibus',
    company: 'Metrô SP',
    booked: false,
    departureLocation: 'Casa - Vila Madalena',
    arrivalLocation: 'Allianz Parque',
    outboundDateTime: '2026-03-21T19:00:00',
    returnDateTime: '2026-03-22T00:30:00',
    notes: 'Pegar metrô linha 2-verde até Sumaré. Evitar Uber — muito caro após show.',
  },
  {
    id: IDS.trv.lolla,
    eventId: IDS.lolla,
    transportType: 'onibus',
    company: 'Shuttle Oficial Lollapalooza',
    booked: true,
    departureLocation: 'Terminal Interlagos',
    arrivalLocation: 'Autódromo de Interlagos',
    outboundDateTime: '2026-03-26T10:00:00',
    returnDateTime: '2026-03-29T23:30:00',
    locatorCode: 'LOLLA-SHUTL-2026',
    notes: 'Shuttle incluso no passaporte. Pegar faixa amarela na entrada.',
  },
  {
    id: IDS.trv.mac,
    eventId: IDS.mac,
    transportType: 'carro',
    booked: false,
    departureLocation: 'Casa',
    arrivalLocation: 'Cine Joia - Praça da Sé',
    outboundDateTime: '2026-04-15T20:30:00',
    returnDateTime: '2026-04-16T00:30:00',
    notes: 'Uber ou metrô. Praça da Sé tem vaga no Shopping Luz.',
  },
  {
    id: IDS.trv.c6,
    eventId: IDS.c6,
    transportType: 'aviao',
    company: 'LATAM Airlines',
    booked: true,
    departureLocation: 'Aeroporto de Congonhas (CGH)',
    arrivalLocation: 'Aeroporto de Confins (CNF)',
    outboundDateTime: '2026-05-10T06:30:00',
    returnDateTime: '2026-05-11T22:00:00',
    locatorCode: 'LATAM-XZW441',
    notes: 'Voo de ida às 6h30 — dormir cedo na véspera. Volta no dia seguinte.',
  },
  {
    id: IDS.trv.animeFriends,
    eventId: IDS.animeFriends,
    transportType: 'onibus',
    company: 'EMTU / Metrô SP',
    booked: false,
    departureLocation: 'Jabaquara (Metrô)',
    arrivalLocation: 'São Paulo Expo',
    outboundDateTime: '2026-07-04T09:00:00',
    returnDateTime: '2026-07-05T20:00:00',
    notes: 'Ônibus expresso da estação Jabaquara. Verificar horários no site.',
  },
  {
    id: IDS.trv.rir,
    eventId: IDS.rir,
    transportType: 'aviao',
    company: 'Azul Linhas Aéreas',
    booked: true,
    departureLocation: 'Aeroporto de Viracopos (VCP)',
    arrivalLocation: 'Aeroporto Santos Dumont (SDU)',
    outboundDateTime: '2026-09-16T14:00:00',
    returnDateTime: '2026-09-28T18:30:00',
    locatorCode: 'AZUL-QRT882',
    notes: 'Ida na véspera. Volta um dia após o festival terminar.',
  },
  {
    id: IDS.trv.tameImpala,
    eventId: IDS.tameImpala,
    transportType: 'carro',
    booked: false,
    departureLocation: 'Casa',
    arrivalLocation: 'Espaço Unimed',
    outboundDateTime: '2026-10-08T19:30:00',
    returnDateTime: '2026-10-09T00:30:00',
    notes: 'Espaço Unimed tem estacionamento. Ir de Uber pode ser mais prático.',
  },
  {
    id: IDS.trv.ivete,
    eventId: IDS.ivete,
    transportType: 'aviao',
    company: 'GOL Linhas Aéreas',
    booked: true,
    departureLocation: 'Aeroporto de Congonhas (CGH)',
    arrivalLocation: 'Aeroporto de Salvador (SSA)',
    outboundDateTime: '2026-12-19T08:00:00',
    returnDateTime: '2026-12-22T19:00:00',
    locatorCode: 'GOL-PLM334',
    notes: 'Viagem de 3 dias em Salvador. Chegando um dia antes para curtir a cidade.',
  },
]

// ─── Lodgings ─────────────────────────────────────────────────────────────────

const lodgings: Lodging[] = [
  {
    id: IDS.ldg.acdc,
    eventId: IDS.acdc,
    required: false,
    confirmed: false,
    notes: 'Show em SP, vou dormir em casa.',
  },
  {
    id: IDS.ldg.lolla,
    eventId: IDS.lolla,
    required: true,
    name: 'Hotel Íbis São Paulo Interlagos',
    address: 'Av. Interlagos, 2255 - Santo Amaro, São Paulo - SP',
    checkIn: '2026-03-25',
    checkOut: '2026-03-30',
    price: 3200.0,
    confirmed: true,
    bookingUrl: 'https://booking.com/xxxx',
    notes: '5 noites. Café da manhã não incluso. A 5 min do autódromo de carro.',
  },
  {
    id: IDS.ldg.mac,
    eventId: IDS.mac,
    required: false,
    confirmed: false,
    notes: 'Show em SP, vou dormir em casa.',
  },
  {
    id: IDS.ldg.c6,
    eventId: IDS.c6,
    required: true,
    name: 'Hotel Mercure Belo Horizonte Lourdes',
    address: 'Av. do Contorno, 7315 - Lourdes, Belo Horizonte - MG',
    checkIn: '2026-05-10',
    checkOut: '2026-05-11',
    price: 420.0,
    confirmed: true,
    bookingUrl: 'https://accor.com/hotel/xxxx',
    notes: '1 noite. Café incluso. Perto da Arena Hall.',
  },
  {
    id: IDS.ldg.animeFriends,
    eventId: IDS.animeFriends,
    required: false,
    confirmed: false,
    notes: 'Evento em SP, vou dormir em casa.',
  },
  {
    id: IDS.ldg.rir,
    eventId: IDS.rir,
    required: true,
    name: 'Airbnb Barra da Tijuca',
    address: 'Avenida das Américas - Barra da Tijuca, Rio de Janeiro - RJ',
    checkIn: '2026-09-16',
    checkOut: '2026-09-28',
    price: 8400.0,
    confirmed: true,
    bookingUrl: 'https://airbnb.com/rooms/xxxx',
    notes: 'Apto compartilhado com 3 amigos. 12 noites. A 15 min da Cidade do Rock.',
  },
  {
    id: IDS.ldg.tameImpala,
    eventId: IDS.tameImpala,
    required: false,
    confirmed: false,
    notes: 'Show em SP, vou dormir em casa.',
  },
  {
    id: IDS.ldg.ivete,
    eventId: IDS.ivete,
    required: true,
    name: 'Hotel Pestana Convento do Carmo',
    address: 'Rua do Carmo, 1 - Pelourinho, Salvador - BA',
    checkIn: '2026-12-19',
    checkOut: '2026-12-22',
    price: 2700.0,
    confirmed: true,
    bookingUrl: 'https://pestana.com/hotel/xxxx',
    notes: '3 noites no Pelourinho. Café incluso. Localização histórica incrível.',
  },
]

// ─── Expenses ─────────────────────────────────────────────────────────────────

const expenses: Expense[] = [
  // AC/DC
  {
    id: 'exp-acdc-1',
    eventId: IDS.acdc,
    category: 'ingresso',
    description: 'Ingresso Pista Premium + taxa',
    amount: 979.0,
    expenseDate: '2025-11-15',
    createdAt: ts('2025-11-15'),
  },
  {
    id: 'exp-acdc-2',
    eventId: IDS.acdc,
    category: 'transporte',
    description: 'Uber ida e volta estimado',
    amount: 80.0,
    expenseDate: '2026-03-21',
    createdAt: ts('2025-12-01'),
  },
  {
    id: 'exp-acdc-3',
    eventId: IDS.acdc,
    category: 'alimentacao',
    description: 'Jantar antes do show',
    amount: 120.0,
    expenseDate: '2026-03-21',
    createdAt: ts('2026-01-10'),
  },
  {
    id: 'exp-acdc-4',
    eventId: IDS.acdc,
    category: 'merch',
    description: 'Camiseta oficial AC/DC (estimado)',
    amount: 220.0,
    expenseDate: '2026-03-21',
    createdAt: ts('2026-02-01'),
  },

  // Lollapalooza
  {
    id: 'exp-lolla-1',
    eventId: IDS.lolla,
    category: 'ingresso',
    description: 'Passaporte 4 dias Pista + taxa',
    amount: 1308.0,
    expenseDate: '2025-10-25',
    createdAt: ts('2025-10-25'),
  },
  {
    id: 'exp-lolla-2',
    eventId: IDS.lolla,
    category: 'hospedagem',
    description: 'Hotel Íbis - 5 noites',
    amount: 3200.0,
    expenseDate: '2026-01-10',
    createdAt: ts('2026-01-10'),
  },
  {
    id: 'exp-lolla-3',
    eventId: IDS.lolla,
    category: 'alimentacao',
    description: 'Alimentação estimada 4 dias',
    amount: 600.0,
    expenseDate: '2026-03-26',
    createdAt: ts('2026-02-01'),
  },
  {
    id: 'exp-lolla-4',
    eventId: IDS.lolla,
    category: 'merch',
    description: 'Camiseta Lollapalooza (estimado)',
    amount: 180.0,
    expenseDate: '2026-03-27',
    createdAt: ts('2026-02-01'),
  },
  {
    id: 'exp-lolla-5',
    eventId: IDS.lolla,
    category: 'extras',
    description: 'Protetor solar, mochila, garrafa',
    amount: 130.0,
    expenseDate: '2026-03-10',
    createdAt: ts('2026-03-05'),
  },

  // Mac DeMarco
  {
    id: 'exp-mac-1',
    eventId: IDS.mac,
    category: 'ingresso',
    description: 'Ingresso Área Geral + taxa',
    amount: 308.0,
    expenseDate: '2026-01-08',
    createdAt: ts('2026-01-08'),
  },
  {
    id: 'exp-mac-2',
    eventId: IDS.mac,
    category: 'transporte',
    description: 'Uber ida e volta',
    amount: 75.0,
    expenseDate: '2026-04-15',
    createdAt: ts('2026-01-20'),
  },
  {
    id: 'exp-mac-3',
    eventId: IDS.mac,
    category: 'alimentacao',
    description: 'Jantar e bebidas',
    amount: 95.0,
    expenseDate: '2026-04-15',
    createdAt: ts('2026-01-20'),
  },

  // C6 Transmission
  {
    id: 'exp-c6-1',
    eventId: IDS.c6,
    category: 'ingresso',
    description: 'Ingresso Pista + taxa',
    amount: 495.0,
    expenseDate: '2026-01-20',
    createdAt: ts('2026-01-20'),
  },
  {
    id: 'exp-c6-2',
    eventId: IDS.c6,
    category: 'transporte',
    description: 'Passagem aérea CGH→CNF ida e volta (LATAM)',
    amount: 890.0,
    expenseDate: '2026-02-01',
    createdAt: ts('2026-02-01'),
  },
  {
    id: 'exp-c6-3',
    eventId: IDS.c6,
    category: 'hospedagem',
    description: 'Hotel Mercure BH - 1 noite',
    amount: 420.0,
    expenseDate: '2026-02-01',
    createdAt: ts('2026-02-01'),
  },
  {
    id: 'exp-c6-4',
    eventId: IDS.c6,
    category: 'alimentacao',
    description: 'Alimentação em BH (2 dias)',
    amount: 200.0,
    expenseDate: '2026-05-10',
    createdAt: ts('2026-03-01'),
  },
  {
    id: 'exp-c6-5',
    eventId: IDS.c6,
    category: 'transporte',
    description: 'Transfer aeroporto Confins → hotel',
    amount: 120.0,
    expenseDate: '2026-05-10',
    createdAt: ts('2026-03-01'),
  },

  // Anime Friends
  {
    id: 'exp-anime-1',
    eventId: IDS.animeFriends,
    category: 'ingresso',
    description: 'Ingresso 2 dias + taxa',
    amount: 176.0,
    expenseDate: '2026-02-05',
    createdAt: ts('2026-02-05'),
  },
  {
    id: 'exp-anime-2',
    eventId: IDS.animeFriends,
    category: 'merch',
    description: 'Compras na feira (mangás, figures)',
    amount: 350.0,
    expenseDate: '2026-07-04',
    createdAt: ts('2026-03-01'),
  },
  {
    id: 'exp-anime-3',
    eventId: IDS.animeFriends,
    category: 'alimentacao',
    description: 'Alimentação 2 dias',
    amount: 150.0,
    expenseDate: '2026-07-04',
    createdAt: ts('2026-03-01'),
  },
  {
    id: 'exp-anime-4',
    eventId: IDS.animeFriends,
    category: 'extras',
    description: 'Fantasia para cosplay',
    amount: 280.0,
    expenseDate: '2026-06-15',
    createdAt: ts('2026-04-01'),
  },

  // Rock in Rio
  {
    id: 'exp-rir-1',
    eventId: IDS.rir,
    category: 'ingresso',
    description: 'Passaporte 2 dias Pista + taxa',
    amount: 1907.5,
    expenseDate: '2025-12-10',
    createdAt: ts('2025-12-10'),
  },
  {
    id: 'exp-rir-2',
    eventId: IDS.rir,
    category: 'transporte',
    description: 'Passagem aérea VCP→SDU (Azul)',
    amount: 1200.0,
    expenseDate: '2026-01-15',
    createdAt: ts('2026-01-15'),
  },
  {
    id: 'exp-rir-3',
    eventId: IDS.rir,
    category: 'hospedagem',
    description: 'Airbnb Barra da Tijuca - 12 noites (minha parte)',
    amount: 2100.0,
    expenseDate: '2026-02-01',
    createdAt: ts('2026-02-01'),
  },
  {
    id: 'exp-rir-4',
    eventId: IDS.rir,
    category: 'alimentacao',
    description: 'Alimentação estimada 12 dias',
    amount: 1500.0,
    expenseDate: '2026-09-17',
    createdAt: ts('2026-03-01'),
  },
  {
    id: 'exp-rir-5',
    eventId: IDS.rir,
    category: 'merch',
    description: 'Camiseta e lembrança Rock in Rio',
    amount: 250.0,
    expenseDate: '2026-09-17',
    createdAt: ts('2026-03-01'),
  },

  // Tame Impala
  {
    id: 'exp-tame-1',
    eventId: IDS.tameImpala,
    category: 'ingresso',
    description: 'Ingresso VIP (estimado, a comprar)',
    amount: 708.5,
    expenseDate: '2026-10-08',
    createdAt: ts('2026-03-10'),
  },
  {
    id: 'exp-tame-2',
    eventId: IDS.tameImpala,
    category: 'transporte',
    description: 'Uber ida e volta (estimado)',
    amount: 90.0,
    expenseDate: '2026-10-08',
    createdAt: ts('2026-03-10'),
  },
  {
    id: 'exp-tame-3',
    eventId: IDS.tameImpala,
    category: 'alimentacao',
    description: 'Jantar antes do show (estimado)',
    amount: 110.0,
    expenseDate: '2026-10-08',
    createdAt: ts('2026-03-10'),
  },

  // Ivete Sangalo
  {
    id: 'exp-ivete-1',
    eventId: IDS.ivete,
    category: 'ingresso',
    description: 'Ingresso Cadeira Superior + taxa',
    amount: 352.0,
    expenseDate: '2026-02-20',
    createdAt: ts('2026-02-20'),
  },
  {
    id: 'exp-ivete-2',
    eventId: IDS.ivete,
    category: 'transporte',
    description: 'Passagem aérea CGH→SSA (GOL)',
    amount: 980.0,
    expenseDate: '2026-02-20',
    createdAt: ts('2026-02-20'),
  },
  {
    id: 'exp-ivete-3',
    eventId: IDS.ivete,
    category: 'hospedagem',
    description: 'Hotel Pestana Convento do Carmo - 3 noites',
    amount: 2700.0,
    expenseDate: '2026-02-20',
    createdAt: ts('2026-02-20'),
  },
  {
    id: 'exp-ivete-4',
    eventId: IDS.ivete,
    category: 'alimentacao',
    description: 'Restaurantes em Salvador (3 dias)',
    amount: 500.0,
    expenseDate: '2026-12-20',
    createdAt: ts('2026-03-01'),
  },
  {
    id: 'exp-ivete-5',
    eventId: IDS.ivete,
    category: 'extras',
    description: 'Passeios turísticos em Salvador',
    amount: 200.0,
    expenseDate: '2026-12-20',
    createdAt: ts('2026-03-01'),
  },
]

// ─── Itinerary ─────────────────────────────────────────────────────────────────

const itinerary: ItineraryItem[] = [
  // AC/DC
  {
    id: 'itn-acdc-1',
    eventId: IDS.acdc,
    order: 0,
    dateTime: '2026-03-21T18:30:00',
    title: 'Jantar no Outback Higienópolis',
    description: 'Jantar rápido antes do show.',
    done: false,
  },
  {
    id: 'itn-acdc-2',
    eventId: IDS.acdc,
    order: 1,
    dateTime: '2026-03-21T19:45:00',
    title: 'Pegar metrô linha 2 em Paulista',
    description: 'Descer na estação Sumaré.',
    done: false,
  },
  {
    id: 'itn-acdc-3',
    eventId: IDS.acdc,
    order: 2,
    dateTime: '2026-03-21T20:30:00',
    title: 'Chegar no Allianz Parque e entrar',
    description: 'Passar pelo credenciamento com ingresso digital.',
    done: false,
  },
  {
    id: 'itn-acdc-4',
    eventId: IDS.acdc,
    order: 3,
    dateTime: '2026-03-21T21:00:00',
    title: 'Show AC/DC começa',
    done: false,
  },
  {
    id: 'itn-acdc-5',
    eventId: IDS.acdc,
    order: 4,
    dateTime: '2026-03-22T00:00:00',
    title: 'Retorno para casa',
    description: 'Metrô até Paulista, depois caminhar ou Uber curto.',
    done: false,
  },

  // Lollapalooza
  {
    id: 'itn-lolla-1',
    eventId: IDS.lolla,
    order: 0,
    dateTime: '2026-03-25T14:00:00',
    title: 'Check-in no hotel',
    description: 'Íbis Interlagos — deixar malas e descansar.',
    done: false,
  },
  {
    id: 'itn-lolla-2',
    eventId: IDS.lolla,
    order: 1,
    dateTime: '2026-03-26T10:30:00',
    title: 'Credenciamento - pegar pulseira Lolla',
    description: 'Levar documento de identidade + QR Code.',
    done: false,
  },
  {
    id: 'itn-lolla-3',
    eventId: IDS.lolla,
    order: 2,
    dateTime: '2026-03-26T12:00:00',
    title: 'Dia 1 do festival',
    description: 'Olivia Rodrigo headliner. Chegar cedo para os shows das primeiras atrações.',
    done: false,
  },
  {
    id: 'itn-lolla-4',
    eventId: IDS.lolla,
    order: 3,
    dateTime: '2026-03-29T12:00:00',
    title: 'Dia 4 - Billie Eilish headliner',
    description: 'Último dia. Guardar energia!',
    done: false,
  },
  {
    id: 'itn-lolla-5',
    eventId: IDS.lolla,
    order: 4,
    dateTime: '2026-03-30T11:00:00',
    title: 'Check-out do hotel e retorno',
    description: 'Pegar Uber até o aeroporto ou rodoviária.',
    done: false,
  },

  // Mac DeMarco
  {
    id: 'itn-mac-1',
    eventId: IDS.mac,
    order: 0,
    dateTime: '2026-04-15T20:00:00',
    title: 'Saída de casa',
    done: false,
  },
  {
    id: 'itn-mac-2',
    eventId: IDS.mac,
    order: 1,
    dateTime: '2026-04-15T21:00:00',
    title: 'Chegar no Cine Joia',
    description: 'Praça da Sé. Ir bem cedo — casa pequena e vai lotar.',
    done: false,
  },
  {
    id: 'itn-mac-3',
    eventId: IDS.mac,
    order: 2,
    dateTime: '2026-04-15T22:00:00',
    title: 'Mac DeMarco sobe ao palco',
    done: false,
  },
  {
    id: 'itn-mac-4',
    eventId: IDS.mac,
    order: 3,
    dateTime: '2026-04-16T00:30:00',
    title: 'Retorno para casa',
    done: false,
  },

  // C6 Transmission
  {
    id: 'itn-c6-1',
    eventId: IDS.c6,
    order: 0,
    dateTime: '2026-05-10T04:30:00',
    title: 'Acordar e ir para Congonhas',
    description: 'Voo às 6h30 — sair com bastante antecedência.',
    done: false,
  },
  {
    id: 'itn-c6-2',
    eventId: IDS.c6,
    order: 1,
    dateTime: '2026-05-10T08:00:00',
    title: 'Chegada em Confins (BH)',
    description: 'Pegar transfer para o hotel.',
    done: false,
  },
  {
    id: 'itn-c6-3',
    eventId: IDS.c6,
    order: 2,
    dateTime: '2026-05-10T14:00:00',
    title: 'Entrada no festival C6 Transmission',
    done: false,
  },
  {
    id: 'itn-c6-4',
    eventId: IDS.c6,
    order: 3,
    dateTime: '2026-05-11T09:00:00',
    title: 'Café da manhã no hotel e check-out',
    done: false,
  },
  {
    id: 'itn-c6-5',
    eventId: IDS.c6,
    order: 4,
    dateTime: '2026-05-11T22:00:00',
    title: 'Voo de volta para São Paulo',
    done: false,
  },

  // Anime Friends
  {
    id: 'itn-anime-1',
    eventId: IDS.animeFriends,
    order: 0,
    dateTime: '2026-07-04T08:30:00',
    title: 'Sair de casa para o SP Expo',
    description: 'Ônibus da Jabaquara.',
    done: false,
  },
  {
    id: 'itn-anime-2',
    eventId: IDS.animeFriends,
    order: 1,
    dateTime: '2026-07-04T10:00:00',
    title: 'Abertura das portas - Dia 1',
    description: 'Prioridade: estandes de mangá e área de autógrafos.',
    done: false,
  },
  {
    id: 'itn-anime-3',
    eventId: IDS.animeFriends,
    order: 2,
    dateTime: '2026-07-05T10:00:00',
    title: 'Dia 2 - Cosplay',
    description: 'Usar a fantasia e participar do concurso de cosplay.',
    done: false,
  },
  {
    id: 'itn-anime-4',
    eventId: IDS.animeFriends,
    order: 3,
    dateTime: '2026-07-05T19:00:00',
    title: 'Encerramento e retorno',
    done: false,
  },

  // Rock in Rio
  {
    id: 'itn-rir-1',
    eventId: IDS.rir,
    order: 0,
    dateTime: '2026-09-16T14:00:00',
    title: 'Embarque em Viracopos',
    description: 'Voo Azul para Santos Dumont.',
    done: false,
  },
  {
    id: 'itn-rir-2',
    eventId: IDS.rir,
    order: 1,
    dateTime: '2026-09-16T17:00:00',
    title: 'Check-in no Airbnb Barra da Tijuca',
    done: false,
  },
  {
    id: 'itn-rir-3',
    eventId: IDS.rir,
    order: 2,
    dateTime: '2026-09-17T12:00:00',
    title: 'Dia 1 na Cidade do Rock',
    description: 'Chegar cedo para aproveitar toda a estrutura.',
    done: false,
  },
  {
    id: 'itn-rir-4',
    eventId: IDS.rir,
    order: 3,
    dateTime: '2026-09-20T12:00:00',
    title: 'Dia 2 na Cidade do Rock',
    done: false,
  },
  {
    id: 'itn-rir-5',
    eventId: IDS.rir,
    order: 4,
    dateTime: '2026-09-28T18:30:00',
    title: 'Voo de volta para São Paulo',
    done: false,
  },

  // Tame Impala
  {
    id: 'itn-tame-1',
    eventId: IDS.tameImpala,
    order: 0,
    dateTime: '2026-10-08T19:30:00',
    title: 'Sair de casa',
    done: false,
  },
  {
    id: 'itn-tame-2',
    eventId: IDS.tameImpala,
    order: 1,
    dateTime: '2026-10-08T20:30:00',
    title: 'Chegar no Espaço Unimed',
    done: false,
  },
  {
    id: 'itn-tame-3',
    eventId: IDS.tameImpala,
    order: 2,
    dateTime: '2026-10-08T21:30:00',
    title: 'Tame Impala começa',
    done: false,
  },
  {
    id: 'itn-tame-4',
    eventId: IDS.tameImpala,
    order: 3,
    dateTime: '2026-10-09T00:00:00',
    title: 'Retorno',
    done: false,
  },

  // Ivete Sangalo
  {
    id: 'itn-ivete-1',
    eventId: IDS.ivete,
    order: 0,
    dateTime: '2026-12-19T07:00:00',
    title: 'Embarque em Congonhas',
    description: 'Voo GOL para Salvador.',
    done: false,
  },
  {
    id: 'itn-ivete-2',
    eventId: IDS.ivete,
    order: 1,
    dateTime: '2026-12-19T10:00:00',
    title: 'Chegada em Salvador e check-in',
    description: 'Hotel Pestana no Pelourinho.',
    done: false,
  },
  {
    id: 'itn-ivete-3',
    eventId: IDS.ivete,
    order: 2,
    dateTime: '2026-12-19T15:00:00',
    title: 'Passeio no Pelourinho',
    description: 'Conhecer o centro histórico.',
    done: false,
  },
  {
    id: 'itn-ivete-4',
    eventId: IDS.ivete,
    order: 3,
    dateTime: '2026-12-20T18:00:00',
    title: 'Jantar e seguir para a Arena Fonte Nova',
    done: false,
  },
  {
    id: 'itn-ivete-5',
    eventId: IDS.ivete,
    order: 4,
    dateTime: '2026-12-22T19:00:00',
    title: 'Voo de volta para São Paulo',
    done: false,
  },
]

// ─── Checklist ─────────────────────────────────────────────────────────────────

const checklist: ChecklistItem[] = [
  // AC/DC
  { id: 'chk-acdc-1', eventId: IDS.acdc, label: 'Confirmar ingresso digital no app', done: true, isDefault: false, order: 0 },
  { id: 'chk-acdc-2', eventId: IDS.acdc, label: 'Carregar celular (power bank)', done: false, isDefault: false, order: 1 },
  { id: 'chk-acdc-3', eventId: IDS.acdc, label: 'Verificar regras de entrada do Allianz', done: true, isDefault: false, order: 2 },
  { id: 'chk-acdc-4', eventId: IDS.acdc, label: 'Levar documento de identidade', done: false, isDefault: true, order: 3 },
  { id: 'chk-acdc-5', eventId: IDS.acdc, label: 'Separar roupa confortável', done: false, isDefault: false, order: 4 },
  { id: 'chk-acdc-6', eventId: IDS.acdc, label: 'Verificar previsão do tempo', done: false, isDefault: false, order: 5 },

  // Lollapalooza
  { id: 'chk-lolla-1', eventId: IDS.lolla, label: 'Fazer mapa dos palcos e horários', done: true, isDefault: false, order: 0 },
  { id: 'chk-lolla-2', eventId: IDS.lolla, label: 'Separar mochila pequena', done: true, isDefault: false, order: 1 },
  { id: 'chk-lolla-3', eventId: IDS.lolla, label: 'Comprar protetor solar FPS 50', done: true, isDefault: false, order: 2 },
  { id: 'chk-lolla-4', eventId: IDS.lolla, label: 'Levar garrafa d\'água reutilizável', done: false, isDefault: true, order: 3 },
  { id: 'chk-lolla-5', eventId: IDS.lolla, label: 'Confirmar reserva do hotel', done: true, isDefault: false, order: 4 },
  { id: 'chk-lolla-6', eventId: IDS.lolla, label: 'Baixar app oficial do Lollapalooza', done: false, isDefault: false, order: 5 },
  { id: 'chk-lolla-7', eventId: IDS.lolla, label: 'Imprimir voucher do shuttle', done: false, isDefault: false, order: 6 },
  { id: 'chk-lolla-8', eventId: IDS.lolla, label: 'Levar capa de chuva', done: false, isDefault: false, order: 7 },

  // Mac DeMarco
  { id: 'chk-mac-1', eventId: IDS.mac, label: 'Confirmar ingresso no Sympla', done: true, isDefault: false, order: 0 },
  { id: 'chk-mac-2', eventId: IDS.mac, label: 'Levar RG', done: false, isDefault: true, order: 1 },
  { id: 'chk-mac-3', eventId: IDS.mac, label: 'Verificar horário de abertura das portas', done: true, isDefault: false, order: 2 },
  { id: 'chk-mac-4', eventId: IDS.mac, label: 'Pedir Uber com antecedência', done: false, isDefault: false, order: 3 },
  { id: 'chk-mac-5', eventId: IDS.mac, label: 'Comer antes (casa pequena, sem muita comida)', done: false, isDefault: false, order: 4 },
  { id: 'chk-mac-6', eventId: IDS.mac, label: 'Separar roupas', done: false, isDefault: false, order: 5 },

  // C6 Transmission
  { id: 'chk-c6-1', eventId: IDS.c6, label: 'Confirmar voo LATAM online', done: true, isDefault: false, order: 0 },
  { id: 'chk-c6-2', eventId: IDS.c6, label: 'Fazer check-in online (24h antes)', done: false, isDefault: false, order: 1 },
  { id: 'chk-c6-3', eventId: IDS.c6, label: 'Confirmar reserva do hotel em BH', done: true, isDefault: false, order: 2 },
  { id: 'chk-c6-4', eventId: IDS.c6, label: 'Separar mala de mão', done: false, isDefault: false, order: 3 },
  { id: 'chk-c6-5', eventId: IDS.c6, label: 'Levar documento + passagem impressa', done: false, isDefault: true, order: 4 },
  { id: 'chk-c6-6', eventId: IDS.c6, label: 'Pesquisar restaurantes em BH', done: true, isDefault: false, order: 5 },
  { id: 'chk-c6-7', eventId: IDS.c6, label: 'Verificar previsão do tempo em BH', done: false, isDefault: false, order: 6 },

  // Anime Friends
  { id: 'chk-anime-1', eventId: IDS.animeFriends, label: 'Confirmar ingresso no Sympla', done: true, isDefault: false, order: 0 },
  { id: 'chk-anime-2', eventId: IDS.animeFriends, label: 'Preparar fantasia para cosplay', done: false, isDefault: false, order: 1 },
  { id: 'chk-anime-3', eventId: IDS.animeFriends, label: 'Levar sacola extra para compras', done: false, isDefault: false, order: 2 },
  { id: 'chk-anime-4', eventId: IDS.animeFriends, label: 'Verificar programação de painéis', done: false, isDefault: false, order: 3 },
  { id: 'chk-anime-5', eventId: IDS.animeFriends, label: 'Separar dinheiro em espécie', done: false, isDefault: false, order: 4 },
  { id: 'chk-anime-6', eventId: IDS.animeFriends, label: 'Levar câmera fotográfica', done: false, isDefault: false, order: 5 },
  { id: 'chk-anime-7', eventId: IDS.animeFriends, label: 'Verificar horário do ônibus da Jabaquara', done: false, isDefault: false, order: 6 },

  // Rock in Rio
  { id: 'chk-rir-1', eventId: IDS.rir, label: 'Check-in online do voo Azul', done: false, isDefault: false, order: 0 },
  { id: 'chk-rir-2', eventId: IDS.rir, label: 'Confirmar Airbnb com anfitriã', done: true, isDefault: false, order: 1 },
  { id: 'chk-rir-3', eventId: IDS.rir, label: 'Montar lista de atrações prioritárias', done: false, isDefault: false, order: 2 },
  { id: 'chk-rir-4', eventId: IDS.rir, label: 'Levar protetor solar e hidratante', done: false, isDefault: true, order: 3 },
  { id: 'chk-rir-5', eventId: IDS.rir, label: 'Separar roupas para 12 dias', done: false, isDefault: false, order: 4 },
  { id: 'chk-rir-6', eventId: IDS.rir, label: 'Confirmar passagens com amigos', done: true, isDefault: false, order: 5 },
  { id: 'chk-rir-7', eventId: IDS.rir, label: 'Levar power bank carregado', done: false, isDefault: false, order: 6 },
  { id: 'chk-rir-8', eventId: IDS.rir, label: 'Verificar regras da Cidade do Rock', done: false, isDefault: false, order: 7 },

  // Tame Impala
  { id: 'chk-tame-1', eventId: IDS.tameImpala, label: 'Comprar ingresso VIP no Eventim', done: false, isDefault: false, order: 0 },
  { id: 'chk-tame-2', eventId: IDS.tameImpala, label: 'Verificar set list de outros shows da turnê', done: false, isDefault: false, order: 1 },
  { id: 'chk-tame-3', eventId: IDS.tameImpala, label: 'Reservar Uber com antecedência', done: false, isDefault: false, order: 2 },
  { id: 'chk-tame-4', eventId: IDS.tameImpala, label: 'Levar RG', done: false, isDefault: true, order: 3 },
  { id: 'chk-tame-5', eventId: IDS.tameImpala, label: 'Escutar discografia atualizada', done: false, isDefault: false, order: 4 },
  { id: 'chk-tame-6', eventId: IDS.tameImpala, label: 'Combinar com amigos sobre ponto de encontro', done: false, isDefault: false, order: 5 },

  // Ivete Sangalo
  { id: 'chk-ivete-1', eventId: IDS.ivete, label: 'Fazer check-in online do voo GOL', done: false, isDefault: false, order: 0 },
  { id: 'chk-ivete-2', eventId: IDS.ivete, label: 'Confirmar reserva hotel Pestana', done: true, isDefault: false, order: 1 },
  { id: 'chk-ivete-3', eventId: IDS.ivete, label: 'Separar roupas para 3 dias (clima quente)', done: false, isDefault: false, order: 2 },
  { id: 'chk-ivete-4', eventId: IDS.ivete, label: 'Pesquisar restaurantes típicos em Salvador', done: false, isDefault: false, order: 3 },
  { id: 'chk-ivete-5', eventId: IDS.ivete, label: 'Levar protetor solar SPF 50', done: false, isDefault: true, order: 4 },
  { id: 'chk-ivete-6', eventId: IDS.ivete, label: 'Confirmar ingresso no Tickets for Fun', done: true, isDefault: false, order: 5 },
  { id: 'chk-ivete-7', eventId: IDS.ivete, label: 'Levar câmera ou verificar câmera do celular', done: false, isDefault: false, order: 6 },
  { id: 'chk-ivete-8', eventId: IDS.ivete, label: 'Verificar câmbio (levar dinheiro em espécie)', done: false, isDefault: false, order: 7 },
]

// ─── Reflections (only for events marked concluido — none in this demo set,
//     but we add two as if they were completed early for richness) ──────────────

const reflections: EventReflection[] = []

// ─── Main export ──────────────────────────────────────────────────────────────

export function getDemoData(): {
  events: Event[]
  tickets: Ticket[]
  travels: Travel[]
  lodgings: Lodging[]
  expenses: Expense[]
  itinerary: ItineraryItem[]
  checklist: ChecklistItem[]
  reflections: EventReflection[]
} {
  return {
    events,
    tickets,
    travels,
    lodgings,
    expenses,
    itinerary,
    checklist,
    reflections,
  }
}
